name: nordic-homes

services:
  app:
    build: .
    command: gunicorn nordichomes.wsgi:application --bind 0.0.0.0:8000
    container_name: django-app
    ports:
      - 8000:8000
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 30s
    restart: unless-stopped

  nginx:
    image: nginx:1.29.0-alpine
    depends_on: 
      - app
    ports: 
      - "80:80"
    volumes:
      - static_data:/var/www/html/static
      - media_data:/var/www/html/media
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  static_data:
  media_data:
  postgres_data:
